config/routes.rb
Rails.application.routes.draw do
  # get "posts" => "posts/index"
  # get "posts/new" => "posts/new"
  resources :posts
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    
    validates :title, presence: true, length: { maximum: 20 }
    validates :start_at, presence: true
    validates :end_at, presence: true
    validates :memo, length: { maximum: 140 }
    def end_correct
        errors.add(:end_at,"は開始日の後の日付から選択してください")
        if post.start_at > post.end_at
        end
    end
        
    validate :end_correct
    def end_correct
        errors.add(:end_at, "は開始日より後の日付から選択してください") unless
        self.start_at <= self.end_at 
        end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end
    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
        # 投稿データが作成された場合
        if @post.save
            flash[:success] = "投稿を作成しました"
            redirect_to posts_path
        else
            flash.now[:failure] = "投稿を作成できませんでした"
            render :new,status: :unprocessable_entity
            
        end
    end


    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        flash[:notice] = "予定を削除しました"
        redirect_to :posts
    end
   
  
    def show
        @post = Post.find(params[:id])
    end
  
    def edit
        @post = Post.find(params[:id])
    end
  
    def update
        @post = Post.find(params[:id])
     if @post.update(post_params)
       flash[:notice] = "スケジュールを更新しました"
       redirect_to :posts
     else
        flash.now[:failure] = "スケジュールの更新に失敗しました"
        render "edit",status: :unprocessable_entity
     end
    end

    def post_params
        params.require(:post).permit(
            :title,
            :start_at,
            :end_at,
            :allday,
            :memo
        )
    end
  
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
  <nav class="navbar Navbar">
    <div class="container-fluid">
      <p class="text-center Navbar__text">
        スケジュール管理アプリ
      </p>
    </div>
  </nav>
</header>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>予定を編集してください</h2>
<% if flash[:failure] %>
<p class="failure"><%= flash[:failure] %></p>
<% end %>
<%= render "shared/error", obj: @post %>


<%= form_with model: @post do |f| %>
  
    <table>
      <tr>
        <th><%= f.label :title ,"タイトル" %></th>
        <td><%= f.text_field :title %></td>
      </tr>
      <tr>
        <th><%= f.label :start_at ,"開始日" %></th>
        <td><%= f.date_select :start_at %></td>
      </tr>
      <tr>
        <th><%= f.label :end_at ,"終了日" %></th>
        <td><%= f.date_select :end_at %></td>
      </tr>
      <tr>
        <th><%= f.label :end_at ,"終日" %></th>
        <td><%= f.check_box :allday, :as => :boolean %>終日の場合はチェックを入れます</td>
      </tr>
      <tr>
        <th><%= f.label :memo ,"メモ" %></th>
        <td><%= f.text_area :memo %></td>
      </tr>
    </table>
  
    <div>
        <p><%= f.submit "編集を完了する" %></p>
        <p><%= link_to "ユーザー情報一覧に戻る", :posts %></p>
    </div>
<% end %>

app/views/posts/index.html.erb
<h2>予定一覧</h2>
<%= link_to "新規追加", "/posts/new" %>

<% if flash[:success] %>
<p class="success"><%= flash[:success] %></p>
<% end %>

<% if flash[:notice] %>
<p class="notice"><%= flash[:notice] %></p>
<% end %>

<% if flash[:failure] %>
<p class="failure"><%= flash[:failure] %></p>
<% end %>





<div class="table-responsive TableResponsive">
  <table class="table Table">
    <thead>
      <tr>
        <th>ID</th>
        <th>タイトル</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>終日</th>
        <th>更新日時</th>
        <th>メモ</th>
        <th>詳細</th>
        <th>編集</th>
        <th>削除</th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
          <tr>
            <td><%= post.id %></td>
            <td><%= post.title %></td>
            <td><%= post.start_at.strftime("%Y/%m/%d") %></td>
            <td><%= post.end_at.strftime("%Y/%m/%d") %></td>
            <td>
            <% if post.allday == '1' %>
            ○
            <% else post.allday == '0' %>
            <% end %>
            </td>
            <td><%= post.updated_at.to_s(:datetime_jp) %></td>
            <td><%= post.memo %></td>
            <td><%= link_to "詳細", post %></td>
            <td><%= link_to "編集", [:edit, post] %></td>
            <td><%= button_to "削除", post, method: :delete, data: { turbo_confirm: "本当に削除しますか？" } %></td>
            </tr>
          <% end %>
    </tbody>
  </table>
</div>

<footer class="card Footer">
  <div class="card-body FooterBody">
    <p class="FooterBody__count">
      予定合計<span><%= Post.count %></span>件
    </p>

    <p class="FooterBody__datetime">
      本日の日付<%= Date.today %>
    </p>
  </div>
</footer>

app/views/posts/new.html.erb
<h2>予定の新規追加</h2>
<% if flash[:failure] %>
<p class="failure"><%= flash[:failure] %></p>
<% end %>

<%= render "shared/error", obj: @post %>

<%= form_with model:@post do |f| %>
    <table>
        <tr>
            <th><%= f.label :タイトル %></th>
            <td><%= f.text_field :title %><br></td>
        </tr>
        <tr>
            <th><%= f.label :開始日 %></th>
            <td><%= f.date_select :start_at %><br></td>
        </tr>
        <tr>
            <th><%= f.label :終了日　%></th>
            <td><%= f.date_select :end_at %><br></td>
        </tr>   
        <tr>
            <th><%= f.label :終日%></th>
            <td><%= f.check_box :allday, :as => :boolean %>　終日の場合はチェックを入れます</td>
        </tr>    
        <tr>
            <th><%= f.label :メモ %></th>
            <td><%= f.text_area :memo %></td>
        </tr>
    </table>
    
     
 <p><%= f.submit "保存" %></p>
<% end %>

app/views/posts/show.html.erb
<div>
  <ul>
    <li><%= link_to "予定一覧に戻る", :posts %></li>
  </ul>
</div>

<h3><%= @post.title %></h3>
 
<div class="table-responsive TableResponsive">
    <table >
    <tr>
        <th>開始日</th>
        <td><%= @post.start_at %></td>
    </tr>
    <tr>
        <th>終了日</th>
        <td><%= @post.end_at %></td>
    </tr>
    <tr>
        <th>終日</th>
        <td>
            <% if @post.allday == '1' %>
            ○
            <% else @post.allday == '0' %>
            <% end %>
        </td>
    </tr>
    <tr>
        <th>メモ</th>
        <td><%= @post.memo %></td>
    </tr>
    </table>
</div>

<p><%= link_to "編集", edit_post_path %></p>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>